### ISSUE TITLE
How do I use this mod?

### ISSUE THREAD

**Issue by volkswagenfeature** [BinarySpike/blueprint-variables#1]
I see you have a bunch of "blueprint variables"
I'm assuming that if I use one of those in a blueprint, it is basically a placeholder for some new signal/item I can swap in?

Any plans for a quick video or other documentation?

**Comment by BinarySpike** [comment]
You can see some more details on the mod portal: https://mods.factorio.com/mod/blueprint-variables

Also, I put together a basic video on how it works: https://www.youtube.com/watch?v=OwWIePDClpM

You're assumption is basically right.  However, it doesn't work for logistics or filters yet—just circuit conditions and train station names.  Also, I want to make a "calculated" variable that let's you get stack size and any other constants related to the selected item.  I'm also interested in being able to variable'ize recipes, recipe inputs, and recipe outputs.

**Comment by volkswagenfeature** [comment]
Thanks, will definitely check it out, sorry I missed these. It seems like it's going to be pretty interesting working with this and recursive blueprints
